### ISSUE TITLE
运行项目就报错了 Error 

### ISSUE THREAD

**Issue by alitong** [shineM/TreeView#3]
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                          at me.texy.treeview.TreeViewAdapter.onCreateViewHolder(TreeViewAdapter.java:101)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6073)

**Comment by shineM** [comment]
漏了一个background   已修复
